
server:
  port: 9090

spring:

  application:
     name: WHATSAPP-CLONE
  datasource:
    username: admin
    password: Vamsi868876
    url: jdbc:mysql://database-2.cncquc2eufgv.eu-north-1.rds.amazonaws.com:3306/whatsapp_clone
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB
  security:
    user:
      name: user
      password: password



      